# .github/workflows/ci-main.yml

name: CI - Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      java-version: '21'
      python-version: '3.11'